### ISSUE TITLE
Python 3/Kodi Matrix

### ISSUE THREAD

**Issue by razzeee** [bossanova808/script.service.checkpreviousepisode#3]
Hey there,

will you update this? Do you want any help?

Cheers

**Comment by bossanova808** [comment]
Definitely planning to update at some point but was kind of waiting for Matrix alphas.  I started doing a few py 2 to py 3 updates a while back but at that point there were lots of missing libs etc., so I stalled.

I think that is mostly done now, so I should get back to this.   But feel free to update/PR it if you're in a hurry - I suspect it will take you half the time it does me as  I've only really done one so far (OzWeather, and I haven't submitted that as such yet).

**Comment by razzeee** [comment]
I guess the real question is if you want to do something 2and3 compatable or if you "abandon" python2. I usually only go forward with py3 and create a branch "python2" with the last leia version.

**Comment by bossanova808** [comment]
Yep have just done that here actually :)

In general I plan to create a python2 branch for my addons - for Leia and below, and would only bother with critical fixes if absolutely necessary

And then master carries on as Python3 and has any new stuff in it.

Basically, in addition to a few I have actually written,  there is this one, and script.service.playbackresumer, both of which I use but did not write - but they have been abandoned so my plan is to update them and take them over....because, well, I want them to keep working and it's easy enough really.

One question I have - the whole script.service.playbackresumer -> should really be just service.playbackresumer or whatever, right?  But I kinda feel changing the addon id is not worth it as it would break upgrades.  But then again, kind of seem like this is the time to do it, if any, with this big general change in addons.

Thoughts?

**Comment by razzeee** [comment]
So yeah, in general, if you want to break, this is probably the time.

Still, users will mostly be able to migrate fine, if a new version of their addon is out when they install. I don't think changing this detail will improve anyones live @enen92 might have some more insight.

**Comment by bossanova808** [comment]
Yep I agree.  It's pretty trivial really, so will leave it.

I'll try and get to these over the next week or two.

**Comment by bossanova808** [comment]
Merged in...thanks!!
